// Code authored by Dean Edis (DeanTheCoder).
// Anyone is free to copy, modify, use, compile, or distribute this software,
// either in source code form or as a compiled binary, for any purpose.
//
// If you modify the code, please retain this copyright header,
// and consider contributing back to the repository or letting us know
// about your modifications. Your contributions are valued!
//
// THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND.

using DTC.Core;
using DTC.Core.Extensions;
using ReviewG33k.Services;
using ReviewG33k.Services.Checks;

namespace ReviewG33k.Tests;

public sealed class UnusedUsingRoslynCodeReviewCheckTests
{
    [Test]
    public void AnalyzeWhenAddedFileContainsUnusedUsingReportsHint()
    {
        const string source = """
            using System;
            using System.Text;

            public sealed class Sample
            {
                public int Compare(string left, string right) => string.Compare(left, right, StringComparison.Ordinal);
            }
            """;

        var report = AnalyzeSource("A", source, [1, 2, 3, 4, 5, 6, 7]);

        Assert.That(report.Findings, Has.Count.EqualTo(1));
        Assert.That(report.Findings[0].Severity, Is.EqualTo(CodeReviewFindingSeverity.Hint));
        Assert.That(report.Findings[0].Message, Does.Contain("`using System.Text;`"));
    }

    [Test]
    public void AnalyzeWhenUsingIsRequiredDoesNotReport()
    {
        const string source = """
            using System;

            public sealed class Sample
            {
                public Type GetTypeToken() => typeof(string);
            }
            """;

        var report = AnalyzeSource("A", source, [1, 2, 3, 4, 5, 6]);

        Assert.That(report.Findings, Is.Empty);
    }

    [Test]
    public void AnalyzeWhenUnusedUsingExistsInModifiedFileReportsEvenWhenLineIsNotAdded()
    {
        const string source = """
            using System.Text;

            public sealed class Sample
            {
                public int Add(int a, int b) => a + b;
            }
            """;

        var report = AnalyzeSource("M", source, [5]);

        Assert.That(report.Findings, Has.Count.EqualTo(1));
        Assert.That(report.Findings[0].Message, Does.Contain("`using System.Text;`"));
    }

    [Test]
    public void AnalyzeWhenProjectUsesImplicitUsingsReportsRedundantExplicitUsing()
    {
        using var tempDirectory = new TempDirectory();
        tempDirectory.GetFile("Sample.Tests.csproj").WriteAllText("""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
              </PropertyGroup>
            </Project>
            """);
        var generatedGlobalUsingsDirectory = tempDirectory.GetDir("obj/Debug/net8.0");
        generatedGlobalUsingsDirectory.Create();
        generatedGlobalUsingsDirectory.GetFile("Sample.Tests.GlobalUsings.g.cs").WriteAllText("""
            // <auto-generated/>
            global using global::System.Threading.Tasks;
            """);

        var sourcePath = tempDirectory.GetFile("Sample.cs");
        const string source = """
            using System.Threading.Tasks;

            public sealed class Sample
            {
                public Task RunAsync() => Task.CompletedTask;
            }
            """;

        var report = AnalyzeSource(
            "M",
            source,
            [4, 5, 6],
            path: "Sample.cs",
            fullPath: sourcePath.FullName);

        Assert.That(report.Findings, Has.Count.EqualTo(1));
        Assert.That(report.Findings[0].Message, Does.Contain("`using System.Threading.Tasks;`"));
    }

    [Test]
    public void AnalyzeWhenFileHasSyntaxErrorsDoesNotReportUnusedUsings()
    {
        const string source = """
            public sealed class Sample
            {
                public int Add(int a, int b) => a + ;
            }
            """;

        var report = AnalyzeSource("A", source, [1, 2, 3, 4, 5]);

        Assert.That(report.Findings, Is.Empty);
    }

    [Test]
    public void AnalyzeWhenFileHasSemanticErrorsDoesNotReportCs8019UnusedUsings()
    {
        const string source = """
            using System.Text;

            public sealed class Sample
            {
                public MissingType Run() => new MissingType();
            }
            """;

        var report = AnalyzeSource("A", source, [1, 2, 3, 4, 5, 6]);

        Assert.That(report.Findings, Is.Empty);
    }

    [Test]
    public void AnalyzeWhenFileHasSemanticErrorsStillReportsGlobalUsingDuplicate()
    {
        using var tempDirectory = new TempDirectory();
        tempDirectory.GetFile("Sample.Tests.csproj").WriteAllText("""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
              </PropertyGroup>
              <ItemGroup>
                <Using Include="System.Text" />
              </ItemGroup>
            </Project>
            """);

        var sourcePath = tempDirectory.GetFile("Sample.cs");
        const string source = """
            using System.Text;

            public sealed class Sample
            {
                public MissingType Run() => new MissingType();
            }
            """;

        var report = AnalyzeSource(
            "M",
            source,
            [4, 5, 6],
            path: "Sample.cs",
            fullPath: sourcePath.FullName);

        Assert.That(report.Findings, Has.Count.EqualTo(1));
        Assert.That(report.Findings[0].Message, Does.Contain("`using System.Text;`"));
    }

    [Test]
    public void AnalyzeWhenFileContainsUnusedGlobalUsingDoesNotReport()
    {
        const string source = """
            global using System.Text;

            public sealed class Sample
            {
                public int Add(int a, int b) => a + b;
            }
            """;

        var report = AnalyzeSource("A", source, [1, 2, 3, 4, 5, 6]);

        Assert.That(report.Findings, Is.Empty);
    }

    private static CodeSmellReport AnalyzeSource(
        string status,
        string source,
        IReadOnlyCollection<int> addedLineNumbers,
        string path = "Packages/CSharp.Core/Sample.cs",
        string fullPath = null)
    {
        var normalizedSource = (source ?? string.Empty).Replace("\r\n", "\n").Replace('\r', '\n');
        var lines = normalizedSource.Split('\n');
        var changedFile = new CodeReviewChangedFile(
            status,
            path,
            fullPath ?? path,
            normalizedSource,
            lines,
            new HashSet<int>(addedLineNumbers));
        var context = new CodeReviewAnalysisContext(
            [changedFile],
            new HashSet<string>(StringComparer.OrdinalIgnoreCase));

        var report = new CodeSmellReport();
        var check = new UnusedUsingRoslynCodeReviewCheck();
        check.Analyze(context, report);
        return report;
    }
}
